project_id = "siirpzuflcimkhnzvass"

[functions.send-registration-email]
enabled = true
verify_jwt = false
import_map = "./functions/send-registration-email/deno.json"
entrypoint = "./functions/send-registration-email/index.ts"

[functions.send-student-email]
enabled = true
verify_jwt = false
entrypoint = "./functions/send-student-email/index.ts"

[functions.delete-user]
enabled = true
verify_jwt = false
entrypoint = "./functions/delete-user/index.ts"

[functions.send-contact-email]
enabled = true
verify_jwt = false
entrypoint = "./functions/send-contact-email/index.ts"

[functions.storage-usage]
enabled = true
verify_jwt = false
entrypoint = "./functions/storage-usage/index.ts"
