project_id = "siirpzuflcimkhnzvass"

[functions.send-registration-email]
enabled = true
verify_jwt = false
entrypoint = "./functions/send-registration-email/index.ts"

[functions.send-student-email]
enabled = true
verify_jwt = false
entrypoint = "./functions/send-student-email/index.ts"

[functions.delete-user]
enabled = true
verify_jwt = false
entrypoint = "./functions/delete-user/index.ts"

[functions.send-contact-email]
enabled = true
verify_jwt = false
entrypoint = "./functions/send-contact-email/index.ts"

[functions.storage-usage]
enabled = true
verify_jwt = false
entrypoint = "./functions/storage-usage/index.ts"

[functions.purge-old-snapshots]
enabled = true
verify_jwt = false
entrypoint = "./functions/purge-old-snapshots/index.ts"

[functions.resend-student-email]
enabled = true
verify_jwt = false
entrypoint = "./functions/resend-student-email/index.ts"
